# -*- coding: utf-8 -*-
# Part of SolarCells RWA. See LICENSE file for full copyright and licensing details.

"""solar.wallet — Custodial wallet for a SolarCells investor.

One record per wallet. At MVP, only one wallet can be in state 'active'
per investor (decision Q-WAL-01). Multiple wallets may exist in states
'pending', 'frozen', 'closed', or 'failed'.

The wallet address is the on-chain ERC-3643 address where the investor's
Solar Cell Tokens are held. It is generated by the custody provider
(Fireblocks, Copper, BitGo) and registered here via the JSON-RPC API.
"""

import logging
import re
import uuid as uuid_lib

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError

_logger = logging.getLogger(__name__)

# Ethereum address pattern: 0x + 40 hex characters
_ETH_ADDRESS_RE = re.compile(r'^0x[0-9a-fA-F]{40}$')

WALLET_TYPE_SELECTION = [
    ('custodial',      'Custodial (managed by SolarCells)'),
    ('mpc',            'MPC (multi-party computation)'),
    ('self_custodial', 'Self-custodial (investor holds keys)'),
]

PROVIDER_SELECTION = [
    ('fireblocks', 'Fireblocks'),
    ('copper',     'Copper'),
    ('bitgo',      'BitGo'),
    ('other',      'Other'),
]

NETWORK_SELECTION = [
    ('tempo',     'Tempo (Stripe)'),
    ('polygon',   'Polygon'),
    ('base',      'Base (Coinbase)'),
    ('avalanche', 'Avalanche'),
]

WALLET_STATE_SELECTION = [
    ('pending', 'Pending creation'),
    ('active',  'Active'),
    ('frozen',  'Frozen (compliance)'),
    ('closed',  'Closed'),
    ('failed',  'Failed (creation error)'),
]


class SolarWallet(models.Model):
    """Custodial wallet for a SolarCells investor."""

    _name        = 'solar.wallet'
    _description = 'Solar Custodial Wallet'
    _inherit     = ['mail.thread']
    _order       = 'created_at desc'
    _rec_name    = 'address'

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------

    uuid = fields.Char(
        string="UUID",
        required=True,
        copy=False,
        readonly=True,
        index=True,
        default=lambda self: str(uuid_lib.uuid4()),
    )
    partner_id = fields.Many2one(
        'res.partner',
        string="Owner",
        required=True,
        ondelete='restrict',
        index=True,
        tracking=True,
    )

    # ------------------------------------------------------------------
    # Wallet classification
    # ------------------------------------------------------------------

    wallet_type = fields.Selection(
        selection=WALLET_TYPE_SELECTION,
        string="Wallet type",
        required=True,
        default='custodial',
        tracking=True,
    )
    provider = fields.Selection(
        selection=PROVIDER_SELECTION,
        string="Custody provider",
        required=True,
        default='fireblocks',
        tracking=True,
    )
    network = fields.Selection(
        selection=NETWORK_SELECTION,
        string="Blockchain network",
        required=True,
        default='tempo',
        tracking=True,
    )

    # ------------------------------------------------------------------
    # Provider references
    # ------------------------------------------------------------------

    provider_vault_id = fields.Char(
        string="Provider vault ID",
        copy=False,
        index=True,
        help="Unique reference in the custody provider's system (e.g. Fireblocks vault ID).",
    )
    address = fields.Char(
        string="On-chain address",
        copy=False,
        index=True,
        help="ERC-3643 address of the investor's wallet on the blockchain. "
             "Format: 0x followed by 40 hexadecimal characters.",
    )

    # ------------------------------------------------------------------
    # State machine
    # ------------------------------------------------------------------

    state = fields.Selection(
        selection=WALLET_STATE_SELECTION,
        string="State",
        default='pending',
        required=True,
        tracking=True,
        index=True,
    )
    failure_reason = fields.Text(
        string="Failure reason",
        copy=False,
    )
    freeze_reason = fields.Text(
        string="Freeze reason",
        copy=False,
    )

    # ------------------------------------------------------------------
    # On-chain whitelist
    # ------------------------------------------------------------------

    whitelisted_on_chain = fields.Boolean(
        string="Whitelisted on-chain",
        default=False,
        tracking=True,
        help="True once the address has been registered in the on-chain "
             "Transfer Whitelist contract.",
    )
    whitelisted_at = fields.Datetime(
        string="Whitelisted at",
        copy=False,
    )

    # ------------------------------------------------------------------
    # Timeline
    # ------------------------------------------------------------------

    created_at = fields.Datetime(
        string="Created at",
        default=fields.Datetime.now,
        required=True,
        copy=False,
    )
    activated_at = fields.Datetime(string="Activated at",  copy=False)
    frozen_at    = fields.Datetime(string="Frozen at",     copy=False)
    closed_at    = fields.Datetime(string="Closed at",     copy=False)
    last_balance_sync_at = fields.Datetime(
        string="Last balance sync",
        help="Last time the on-chain balance was synchronised from the provider.",
    )

    # ------------------------------------------------------------------
    # Provider metadata
    # ------------------------------------------------------------------

    metadata = fields.Json(
        string="Provider metadata",
        default=dict,
        copy=False,
        help="Raw JSON metadata returned by the custody provider (vault details, "
             "policies, signers, etc.).",
    )

    # ------------------------------------------------------------------
    # Computed
    # ------------------------------------------------------------------

    is_primary = fields.Boolean(
        string="Primary wallet",
        compute='_compute_is_primary',
        store=True,
        help="True if this is the investor's current primary wallet.",
    )

    @api.depends('partner_id.x_primary_wallet_id')
    def _compute_is_primary(self):
        for wallet in self:
            wallet.is_primary = (
                wallet.partner_id.x_primary_wallet_id.id == wallet.id
                if wallet.partner_id.x_primary_wallet_id else False
            )

    # ------------------------------------------------------------------
    # Constraints
    # ------------------------------------------------------------------

    @api.constrains('address')
    def _check_address_format(self):
        """Validate Ethereum-style address format (if provided)."""
        for wallet in self:
            if wallet.address and not _ETH_ADDRESS_RE.match(wallet.address):
                raise ValidationError(_(
                    "Address '%s' is not a valid Ethereum address. "
                    "Expected format: 0x followed by 40 hexadecimal characters."
                ) % wallet.address)

    @api.constrains('address')
    def _check_address_unique(self):
        """Address must be unique across all wallets (if provided)."""
        for wallet in self:
            if not wallet.address:
                continue
            duplicate = self.search([
                ('address', '=', wallet.address),
                ('id', '!=', wallet.id),
            ], limit=1)
            if duplicate:
                raise ValidationError(_(
                    "Address '%s' is already used by wallet %s (owner: %s). "
                    "Each wallet address must be unique."
                ) % (wallet.address, duplicate.uuid, duplicate.partner_id.name))

    @api.constrains('partner_id', 'state')
    def _check_one_active_wallet_per_partner(self):
        """MVP constraint Q-WAL-01: only one 'active' wallet per partner."""
        for wallet in self:
            if wallet.state != 'active':
                continue
            others = self.search([
                ('partner_id', '=', wallet.partner_id.id),
                ('state', '=', 'active'),
                ('id', '!=', wallet.id),
            ], limit=1)
            if others:
                raise ValidationError(_(
                    "Partner '%s' already has an active wallet (%s). "
                    "Only one active wallet per investor is allowed at MVP (Q-WAL-01). "
                    "Freeze or close the existing wallet before activating another."
                ) % (wallet.partner_id.name, others.uuid))

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('uuid'):
                vals['uuid'] = str(uuid_lib.uuid4())
        records = super().create(vals_list)
        for wallet in records:
            self.env['solar.audit.log'].create_audit_entry(
                action_code='wallet.created',
                subject=wallet,
                after={
                    'wallet_type': wallet.wallet_type,
                    'provider':    wallet.provider,
                    'network':     wallet.network,
                    'state':       wallet.state,
                },
            )
        return records

    # ------------------------------------------------------------------
    # State transitions
    # ------------------------------------------------------------------

    def _assert_state(self, expected, action):
        self.ensure_one()
        if self.state not in expected:
            raise UserError(_(
                "Cannot execute '%s': wallet %s is in state '%s'. Expected: %s."
            ) % (action, self.uuid, self.state,
                 ', '.join("'%s'" % s for s in expected)))

    def action_activate(self):
        """pending → active. Called after the provider confirms vault creation.

        Also sets the wallet as the partner's primary wallet if none is set.
        """
        self._assert_state(['pending'], 'Activate')
        before = self.state
        now = fields.Datetime.now()
        self.write({'state': 'active', 'activated_at': now})

        # Set as primary if no primary wallet is set
        if not self.partner_id.x_primary_wallet_id:
            self.partner_id.write({'x_primary_wallet_id': self.id})

        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.activated',
            subject=self,
            before={'state': before},
            after={'state': 'active', 'activated_at': str(now)},
        )
        _logger.info("Wallet %s activated for partner %s.", self.uuid, self.partner_id.name)
        return True

    def action_mark_failed(self, reason=None):
        """pending → failed. Provider returned an error during creation."""
        self._assert_state(['pending'], 'Mark failed')
        self.write({'state': 'failed', 'failure_reason': reason})
        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.creation.failed',
            subject=self,
            after={'state': 'failed', 'failure_reason': reason},
        )
        return True

    def action_whitelist_on_chain(self):
        """Register the wallet address in the on-chain Whitelist contract.

        Idempotent — safe to call multiple times.
        In production, this triggers an Odoo ↔ Tempo Adapter call.
        """
        self.ensure_one()
        if not self.address:
            raise UserError(_(
                "Cannot whitelist wallet %s: no on-chain address is set."
            ) % self.uuid)
        if self.state != 'active':
            raise UserError(_(
                "Cannot whitelist wallet %s: wallet must be 'active' (current: '%s')."
            ) % (self.uuid, self.state))

        if self.whitelisted_on_chain:
            _logger.info("Wallet %s already whitelisted on-chain. Skipping.", self.uuid)
            return True

        now = fields.Datetime.now()
        self.write({'whitelisted_on_chain': True, 'whitelisted_at': now})
        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.whitelisted',
            subject=self,
            after={
                'address':          self.address,
                'whitelisted_at':   str(now),
                'network':          self.network,
            },
        )
        _logger.info("Wallet %s whitelisted on-chain (network: %s).", self.uuid, self.network)
        return True

    def action_freeze(self, reason=None):
        """active → frozen. Called by compliance when AML alert is raised."""
        self._assert_state(['active'], 'Freeze')
        now = fields.Datetime.now()
        self.write({
            'state':        'frozen',
            'frozen_at':    now,
            'freeze_reason': reason or _("No reason provided."),
        })
        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.frozen',
            subject=self,
            after={'state': 'frozen', 'freeze_reason': reason},
        )
        _logger.warning("Wallet %s frozen. Reason: %s", self.uuid, reason)
        return True

    def action_unfreeze(self):
        """frozen → active. Compliance officer clears the freeze."""
        self._assert_state(['frozen'], 'Unfreeze')
        self.write({
            'state':        'active',
            'freeze_reason': False,
        })
        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.unfrozen',
            subject=self,
            after={'state': 'active'},
        )
        return True

    def action_close(self):
        """active / frozen → closed. Final step in account closure."""
        self._assert_state(['active', 'frozen'], 'Close')
        now = fields.Datetime.now()
        self.write({'state': 'closed', 'closed_at': now})

        # If this was the primary wallet, clear the reference
        if self.partner_id.x_primary_wallet_id.id == self.id:
            # Find another active wallet to promote, or clear
            other_active = self.search([
                ('partner_id', '=', self.partner_id.id),
                ('state', '=', 'active'),
                ('id', '!=', self.id),
            ], limit=1)
            self.partner_id.write({
                'x_primary_wallet_id': other_active.id if other_active else False,
            })

        self.env['solar.audit.log'].create_audit_entry(
            action_code='wallet.closed',
            subject=self,
            after={'state': 'closed', 'closed_at': str(now)},
        )
        return True

    # ------------------------------------------------------------------
    # Scheduled actions
    # ------------------------------------------------------------------

    @api.model
    def _cron_verify_whitelist_consistency(self):
        """Daily: flag active wallets with address but not whitelisted on-chain.

        In production, this would also call the blockchain to verify.
        Here it creates an audit warning entry so the ops team can investigate.
        """
        inconsistent = self.search([
            ('state', '=', 'active'),
            ('address', '!=', False),
            ('whitelisted_on_chain', '=', False),
        ])
        for wallet in inconsistent:
            self.env['solar.audit.log'].create_audit_entry(
                action_code='wallet.whitelist.inconsistency',
                subject=wallet,
                after={
                    'address':             wallet.address,
                    'whitelisted_on_chain': False,
                },
            )
            _logger.warning(
                "Wallet %s (partner: %s) has an address but is NOT whitelisted on-chain.",
                wallet.uuid, wallet.partner_id.name,
            )
        return True

    # ------------------------------------------------------------------
    # JSON-RPC API
    # ------------------------------------------------------------------

    @api.model
    def create_wallet_for_partner(self, partner_uuid, provider_vault_id,
                                   address=None, wallet_type='custodial',
                                   provider='fireblocks', network='tempo',
                                   metadata=None):
        """Create a new wallet for an investor and set it as their primary.

        Called by the Node.js backend after the custody provider confirms
        vault creation.

        :param str partner_uuid: The investor's external UUID.
        :param str provider_vault_id: Provider vault reference.
        :param str address: On-chain address (optional at creation, set on activation).
        :param str wallet_type: 'custodial', 'mpc', or 'self_custodial'.
        :param str provider: 'fireblocks', 'copper', 'bitgo', or 'other'.
        :param str network: 'tempo', 'polygon', 'base', or 'avalanche'.
        :param dict metadata: Raw provider metadata.
        :returns: dict with wallet uuid and state.
        """
        partner = self.env['res.partner'].search(
            [('x_uuid', '=', partner_uuid)], limit=1,
        )
        if not partner:
            raise UserError(_("Partner not found for UUID '%s'.") % partner_uuid)

        # Verify KYC is validated before creating a wallet (MVP guard)
        kyc_status = partner.x_kyc_status
        if kyc_status not in ('validated',):
            raise UserError(_(
                "Cannot create wallet for partner '%s': KYC status is '%s'. "
                "KYC must be validated first."
            ) % (partner.name, kyc_status or 'not_started'))

        wallet = self.create({
            'partner_id':       partner.id,
            'wallet_type':      wallet_type,
            'provider':         provider,
            'provider_vault_id': provider_vault_id,
            'address':          address,
            'network':          network,
            'metadata':         metadata or {},
        })

        # Link wallet to partner
        partner.write({'x_wallet_ids': [(4, wallet.id)]})

        _logger.info(
            "Wallet %s created for partner %s (provider: %s, vault: %s).",
            wallet.uuid, partner.name, provider, provider_vault_id,
        )
        return {
            'wallet_uuid': wallet.uuid,
            'state':       wallet.state,
            'partner_uuid': partner_uuid,
        }

    def activate_wallet(self, address=None):
        """Activate this wallet and optionally set the on-chain address.

        :param str address: On-chain address returned by the provider.
        :returns: dict with updated state.
        """
        self.ensure_one()
        if address:
            self.write({'address': address})
        self.action_activate()
        # Auto-whitelist if address is set
        if self.address:
            try:
                self.action_whitelist_on_chain()
            except Exception as exc:
                _logger.error(
                    "Could not whitelist wallet %s on-chain: %s. "
                    "The wallet was activated but whitelist must be retried.",
                    self.uuid, exc,
                )
        return {'wallet_uuid': self.uuid, 'state': self.state}

    def get_wallet_info(self):
        """Return a JSON-safe dict for the frontend."""
        self.ensure_one()
        return {
            'uuid':                 self.uuid,
            'wallet_type':          self.wallet_type,
            'provider':             self.provider,
            'network':              self.network,
            'address':              self.address,
            'state':                self.state,
            'whitelisted_on_chain': self.whitelisted_on_chain,
            'is_primary':           self.is_primary,
            'created_at':           str(self.created_at),
            'activated_at':         str(self.activated_at) if self.activated_at else None,
        }
